In [1]:
import numpy as np

In [2]:
print(np.pi)

3.141592653589793


In [3]:
print(np.cos(np.pi))

-1.0


In [4]:
print(np.sqrt(1.2))

1.0954451150103321


In [5]:
vec2 = np.arange(2,10)
print(vec2)

[2 3 4 5 6 7 8 9]


In [7]:
vec3 = np.arange(2,10,20)
print(vec3)

[2]


In [12]:
mat = np.ones((5,3))
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
mat1 = np.zeros([5,3])
print(mat1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
mat2 = np.eye(4)
print(mat2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
vac4 = np.arange(2,5)
vac5 = np.arange(3,6)
vac6 = vac4*vac5
print(vac4)
print(vac5)
print(vac6)
print(1/vac4)

[2 3 4]
[3 4 5]
[ 6 12 20]
[0.5        0.33333333 0.25      ]


In [37]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
prod=np.matmul(mat,vac4)
print(prod)

[20 47 74]


In [51]:
print(mat)
print(vac4)
print(prod)
print(np.linalg.solve(mat,prod))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 3 4]
[20 47 74]
[-5.6 18.2 -3.6]
